name: build-deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24
    - run: go get .
    - run: go build -o build/snoozybot .
    - uses: actions/upload-artifact@v4
      with:
        name: snoozybot
        path: build/snoozybot

  deploy:
    runs-on: ubuntu-latest
    environment: snoozybot
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: snoozybot
      - uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{ vars.DEPLOY_HOST }}
          PORT: ${{ vars.DEPLOY_PORT }}
          USER: ${{ vars.DEPLOY_USER }}
          KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          TARGET: snoozybot/
          ARGS_MORE: --exclude '/.env' --chmod=Fu=rwx
          POST_SCRIPT: sudo systemctl restart snoozybot.service
